version: "3.3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: 'casino'
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Passw0rd!}
      PGDATA: /data/postgres
    volumes:
       - database:/data/postgres
    ports:
      - "5432:5432"      
    expose:
      - "5432"
    restart: always
volumes:
  database: