server:
  port: 8080

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/casino
    username: postgres
    password: Passw0rd!
  jpa:
    properties.hibernate:
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  admin-user: admin
  admin-password: Adm1n!
  rps-game:
    fair-game: true #if false define next probabilities parts
    ai-wins-part: 79
    human-wins-part: 61
    tie-part: 63